def label = "worker-${UUID.randomUUID().toString()}"

// Slack 알림

podTemplate(label: label, containers: [
// #0 필요한 Pod생성
]) {
  node(label) {

	// 예외처리 구문
	try {
		// Slack - 빌드 시작시

		// #1 Github 소스 가져오기

		// #2 Properties 파일 읽기		

		// 재배포를 위한 tag를 재정의
		def timeStamp = System.currentTimeMillis()
		echo "TimeStamp: ${timeStamp}"
		tag = tag+"-"+timeStamp

		// #3 빌드 Stage

		// #4 Sonarqube 정적분석 Stage

		// #5 컨테이너 이미지 생성 Stage

		// #6 배포 Stage


		// Slack - 빌드 성공시


	} catch(e) {
		// Slack - 빌드 실패시

	}
  }
}
