apiVersion: v1
kind: Service
metadata:
  name: fontend-lab03
  labels:
    name: frontend-lab03
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app:frontend-lab03
  type: NodePort
